[package]
name = "gantry-api"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = {version = "5.5", default-features = false, features = ["tokio"]}
zvariant = {version = "5.4", features = ["option-as-array"]}
serde = {version = "1.0", features = ["derive"]}